shinyUI(pageWithSidebar(
     headerPanel("Graphing corrosion in ships"),
     sidebarPanel(
               radioButtons("dataset", 
                       label = h4("Which data need to be summarized?"),
                       choices = list("All data" = "corrdata", 
                                      "Control data" = "algdata", 
                                      "Treatment data" = "stoltdata"), 
                       selected = "corrdata"),
               hr(),
               selectInput("colorGeneral", 
                       label = h4("Select general ship population color"), 
                       choices = list("Grey" = "Grey", 
                                      "Lightgreen" = "Lightgreen", 
                                      "Lightblue" = "Lightblue"), 
                       selected = 1),
               selectInput("colorTreated", 
                       label = h4("Select treated ship population color"), 
                       choices = list("Black" = "Black", 
                                      "Darkgreen" = "Darkgreen", 
                                      "Darkblue" = "Darkblue"), 
                       selected = 1),
               hr(),
               radioButtons("symbGeneral", 
                            label = h4("Choose a symbol for the control values"),
                            choices = list("open circle" = 1, 
                                   "open triangle" = 2, "open square" = 0), 
                            selected = 1),
               radioButtons("symbTreated", 
                            label = h4("Choose a symbol for the treatment values"),
                            choices = list("full circle" = "16", 
                                   "full triangle" = "17", "cross" = "4"), 
                            selected = "16")
               ), 
     mainPanel(
               h4("Graphical overview"),
               plotOutput("corroplot"),
               h4(textOutput("text2")),
               verbatimTextOutput("summary"),
               tags$div(textOutput("text1"))
               )
     ))